name: chessearn
description: A global chess platform with 1v1 gameplay.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chess_board: ^1.0.1  # Use stable version
  chess: ^0.7.0              # Explicitly add compatible chess version
  http: ^1.2.2
  shared_preferences: ^2.3.2
  country_code_picker: ^3.0.0
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5
  image_picker: ^1.0.0 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/