name: chessearn_new
description: A global chess platform with 1v1 gameplay where players can earn rewards.
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_chess_board: ^1.0.1
  chess: ^0.8.1
  stockfish: ^1.7.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  flutter_stripe: ^11.0.0
  cookie_jar: ^4.0.8
  image_picker: ^1.1.2
  google_sign_in: ^6.3.0 # Fixed to suggested version
  country_code_picker: ^3.0.0
  intl: ^0.20.2
  path_provider: ^2.1.4
  permission_handler: ^11.1.0
  dartchess: ^0.11.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  local_auth: ^2.3.0
  file_picker: ^8.1.2
  shimmer: ^3.0.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  chess: ^0.8.1 # Ensures compatibility with flutter_chess_board

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/king_with_hidden_dollar.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/king_with_hidden_dollar.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/chess_board.png
    - assets/images/coach_avatar.png
    - assets/images/king_with_hidden_dollar.png