"""updated user 

Revision ID: e8351f5772e3
Revises: 0020ddb462ad
Create Date: 2025-05-13 14:56:19.568858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8351f5772e3'
down_revision = '0020ddb462ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('white_player_id', sa.String(length=36), nullable=False),
    sa.Column('black_player_id', sa.String(length=36), nullable=False),
    sa.Column('winner_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('date_played', sa.DateTime(), nullable=True),
    sa.Column('bet_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['white_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('predicted_winner_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['predicted_winner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('photo_filename')

    op.drop_table('bets')
    op.drop_table('games')
    # ### end Alembic commands ###
