"""empty message

Revision ID: f4b03608f574
Revises: 18f14e83af69
Create Date: 2025-05-22 09:21:43.405491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4b03608f574'
down_revision = '18f14e83af69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('white_player_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('black_player_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('winner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_played', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bet_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['users.id'], name='games_black_player_id_fkey'),
    sa.ForeignKeyConstraint(['white_player_id'], ['users.id'], name='games_white_player_id_fkey'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], name='games_winner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='games_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('bets',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('predicted_winner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('won', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('bets_game_id_fkey')),
    sa.ForeignKeyConstraint(['predicted_winner_id'], ['users.id'], name=op.f('bets_predicted_winner_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bets_pkey'))
    )
    # ### end Alembic commands ###
